export const trackedSellers = [
  "ALLO.ua",
  "AT-shop",
  "ChilliStore",
  "Click.ua",
  "Comtrading.ua",
  "Davi.com.ua",
  "EXE.ua",
  "EServer.ua",
  "Fopi.ua",
  "GameShop.ua",
  "HDphone.com.ua",
  "ITbox.ua",
  "Luxmedia.com.ua",
  "LuckyLink.kiev.ua",
  "MOBILE Store",
  "MobiFun Store",
  "My Cloud Store",
  "NewTime.ua",
  "OrangeStore",
  "PARSER.ua",
  "PCshop.UA",
  "SKYMARKET.ua",
  "Toiler.com.ua",
  "VINT.com.ua",
  "Yellow.ua",
  "Zelen Store",
  "aStore",
  "click24.com.ua",
  "clearsound.kyiv.ua",
  "dp-shop",
  "ebox24.lviv.ua",
  "eurobuy.ua",
  "expertonline.com.ua",
  "freephone.in.ua",
  "gstore.com.ua",
  "iBox.kiev.ua",
  "iCenter.in.ua",
  "iCom.net.ua",
  "iMag.ua",
  "iStore.ua",
  "inter.if.ua",
  "swipe.ua",
  "TENDO.com.ua",
  "КТС.ua",
  "Портатив (Portativ.ua)",
  "Скай (skay.ua)",
  "Rozetka.ua",
];
